#!/usr/bin/env ruby
require 'escort'
require 'yamljson'
require 'yamljson/version'

ARGV.unshift('convert')
Escort::App.create do |app|
  app.version Yamljson::VERSION
  app.summary "json2yaml"
  app.description "convert JSON to YAML"

  app.command :convert do |command|
    command.summary "convert JSON to YAML"
    command.options do |opts|
      opts.opt(:input_file,
        'input file',
        :long => '--input-file',
        :type => :string,
      )
      opts.opt(:no_pretty,
        'Do not pretty print converted data (output a single line)',
        :long    => '--pretty',
        :type    => :boolean,
        :default => false,
      )
    end
    command.action do |options, arguments|
      input_file  = options[:global][:commands][:convert][:options][:input_file]
      no_pretty   = options[:global][:commands][:convert][:options][:no_pretty]
      if input_file == nil
        raise "YAML or JSON file must be specified"
      else
        puts Yamljson::yaml2json(input_file, no_pretty)
      end
    end
  end
end
